#!/bin/sh

FILES_PATTERN='(\..+)?$'
FORBIDDEN='contextravel'

git diff --cached --name-only | \
    grep -E $FILES_PATTERN | \
    GREP_COLOR='4;5;37;41' xargs grep --color --with-filename -n $FORBIDDEN && \
    echo 'Commit rejected! Correct contextravel to contexttravel.' && \
    exit 1

exit 0
